#!/usr/bin/python

"eSudo launcher"

import esudo, elementary, sys

if __name__ == "__main__":
    cmd = " ".join(sys.argv[1:])

    start = esudo.eSudo(cmd)

    elementary.run()
    elementary.shutdown()

