#!/bin/sh
mv /usr/bin/gksu /usr/bin/gksu-original
mv /usr/bin/esudo-gksu /usr/bin/gksu
cp -s -f /usr/bin/esudo /usr/bin/gksudo

SUDOER='/etc/sudoers.d/esudo-properties'
CONFIG='/etc/esudo/service'

chmod 0440 $SUDOER
chown root $SUDOER
chgrp root $SUDOER
chown -R root $CONFIG
chgrp -R root $CONFIG
